name: Deploy Package to Cloudsmith
on:
 push:
   branches:
     - main
permissions:
 id-token: write # Necessary for GH Identity Provider to write the JWT token which Cloudsmith needs to read
 contents: read
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.x'
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install setuptools wheel
     - name: Create a Python package
       run: |
         cd mypackage
         python setup.py sdist bdist_wheel
         cd ..
     - name: List package files
       run: ls -l mypackage/dist/
     - name: Get OIDC token
       run: |
         value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
         echo $value
         token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"github-oidc\"}" https://api.cloudsmith.io/openid/interview-ranjan-singh/ | jq -r '.token')
         echo $token
         curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
         echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV
     - name: Push
       id: push
       uses: cloudsmith-io/action@master
       with:
         api-key: ${{ env.CLOUDSMITH_API_KEY }}
         command: "push"
         format: "python"
         owner: "interview-ranjan-singh"
         repo: "mypackage"
         republish: "true" # needed ONLY if version is not changing
         file: "mypackage/dist/*.tar.gz"
